// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDcTazNOE48UwgrhY8XbCkazAGnVCGxNc',
    appId: '1:115837640758:web:50e8a42e399a3f5683f897',
    messagingSenderId: '115837640758',
    projectId: 'onesignalpushnotificatio-744c3',
    authDomain: 'onesignalpushnotificatio-744c3.firebaseapp.com',
    storageBucket: 'onesignalpushnotificatio-744c3.appspot.com',
    measurementId: 'G-DC9LBH1VB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIBW8twH_sVuqbe0YwukKU14_FzqYqEpE',
    appId: '1:115837640758:android:fbbd7ab0fa48a1c183f897',
    messagingSenderId: '115837640758',
    projectId: 'onesignalpushnotificatio-744c3',
    storageBucket: 'onesignalpushnotificatio-744c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHI-Uxcddje2aLIHVLzRR6GpJD0koW4g',
    appId: '1:115837640758:ios:d01c9fba1672251083f897',
    messagingSenderId: '115837640758',
    projectId: 'onesignalpushnotificatio-744c3',
    storageBucket: 'onesignalpushnotificatio-744c3.appspot.com',
    iosBundleId: 'com.example.oneSignalPushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHI-Uxcddje2aLIHVLzRR6GpJD0koW4g',
    appId: '1:115837640758:ios:d01c9fba1672251083f897',
    messagingSenderId: '115837640758',
    projectId: 'onesignalpushnotificatio-744c3',
    storageBucket: 'onesignalpushnotificatio-744c3.appspot.com',
    iosBundleId: 'com.example.oneSignalPushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDcTazNOE48UwgrhY8XbCkazAGnVCGxNc',
    appId: '1:115837640758:web:b76ac2184fcdba7d83f897',
    messagingSenderId: '115837640758',
    projectId: 'onesignalpushnotificatio-744c3',
    authDomain: 'onesignalpushnotificatio-744c3.firebaseapp.com',
    storageBucket: 'onesignalpushnotificatio-744c3.appspot.com',
    measurementId: 'G-8J84LEHTQ2',
  );
}
